using System;

namespace BreachTowerInstaller.Core;

public static class EnvWriter
{
    public static string Build(EnvConfig cfg)
    {
        var ts = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
        return $"""
# =============================================================================
# Breach Tower -- Auto-generated by installer on {ts}
# =============================================================================

# -- Database -----------------------------------------------------------------
DB_PASSWORD={cfg.DbPassword}
DATABASE_URL=postgresql://admin:{cfg.DbPassword}@postgres:5432/breachtower

# -- Auth ---------------------------------------------------------------------
JWT_SECRET={cfg.JwtSecret}
VAULT_PASSWORD={cfg.VaultPassword}

# -- SMTP ---------------------------------------------------------------------
SMTP_HOST={cfg.SmtpHost}
SMTP_PORT={cfg.SmtpPort}
SMTP_USER={cfg.SmtpUser}
SMTP_PASS={cfg.SmtpPass}
ALERT_EMAIL={cfg.AlertEmail}

# -- Slack --------------------------------------------------------------------
SLACK_WEBHOOK={cfg.SlackWebhook}

# -- Dashboard ----------------------------------------------------------------
DASHBOARD_URL={cfg.DashboardUrl}
ALLOWED_ORIGINS={cfg.DashboardUrl}

# -- Scan config --------------------------------------------------------------
SCAN_INTERVAL_HOURS=6
DISABLED_MONITORS=

# -- Intelligence API keys (configure in Settings after install) --------------
HIBP_API_KEY=
BREACH_DIRECTORY_KEY=
LEAKCHECK_API_KEY=
INTELX_API_KEY=
LEAKLOOKUP_API_KEY=
TELEGRAM_API_ID=
TELEGRAM_API_HASH=
PASTEBIN_API_KEY=
PASTEBIN_API_USER_KEY=

# -- Microsoft SSO (optional) -------------------------------------------------
AZURE_CLIENT_ID=
AZURE_TENANT_ID=

# -- Environment --------------------------------------------------------------
ENVIRONMENT=production
""";
    }
}
