package installer

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
	"time"
)

// randomHex returns a cryptographically random hex string of n bytes (2n chars).
func randomHex(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		die("Failed to generate random bytes: " + err.Error())
	}
	return hex.EncodeToString(b)
}

// randomAlphaNum returns a cryptographically random alphanumeric string of length n.
func randomAlphaNum(n int) string {
	const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		die("Failed to generate random bytes: " + err.Error())
	}
	for i, c := range b {
		b[i] = chars[int(c)%len(chars)]
	}
	return string(b)
}

// configureEnv interactively creates .env in installDir.
// Returns true if a fresh .env was written (so callers can wipe pgdata).
func configureEnv() bool {
	envFile := installDir + `\.env`

	if _, err := os.Stat(envFile); err == nil {
		logWarn(".env already exists at " + envFile)
		if !promptYN("Overwrite it?") {
			logInfo("Keeping existing .env.")
			return false
		}
	}

	fmt.Println()
	logInfo("Generating secure secrets automatically...")
	dbPass := randomAlphaNum(24)
	jwtSecret := randomHex(64)
	vaultPass := randomAlphaNum(24)
	logSuccess("Secrets generated.")

	fmt.Println()
	logStep("Configuration")
	logInfo("Press Enter to skip optional fields — configure them later in Settings.")
	fmt.Println()

	alertEmail := prompt("Admin alert email (where breach alerts are sent)", "")
	smtpHost := prompt("SMTP host (e.g. smtp.gmail.com) [optional]", "")
	smtpPort := prompt("SMTP port", "587")
	smtpUser := prompt("SMTP username / email [optional]", "")
	smtpPass := prompt("SMTP password / app password [optional]", "")
	slackWebhook := prompt("Slack webhook URL [optional]", "")
	dashboardURL := prompt("Dashboard public URL", "http://localhost:3000")

	timestamp := time.Now().Format("2006-01-02 15:04:05")

	content := strings.Join([]string{
		"# =============================================================================",
		fmt.Sprintf("# Breach Tower -- Auto-generated by installer on %s", timestamp),
		"# =============================================================================",
		"",
		"# -- Database -----------------------------------------------------------------",
		fmt.Sprintf("DB_PASSWORD=%s", dbPass),
		fmt.Sprintf("DATABASE_URL=postgresql://admin:%s@postgres:5432/breachtower", dbPass),
		"",
		"# -- Auth ---------------------------------------------------------------------",
		fmt.Sprintf("JWT_SECRET=%s", jwtSecret),
		fmt.Sprintf("VAULT_PASSWORD=%s", vaultPass),
		"",
		"# -- SMTP ---------------------------------------------------------------------",
		fmt.Sprintf("SMTP_HOST=%s", smtpHost),
		fmt.Sprintf("SMTP_PORT=%s", smtpPort),
		fmt.Sprintf("SMTP_USER=%s", smtpUser),
		fmt.Sprintf("SMTP_PASS=%s", smtpPass),
		fmt.Sprintf("ALERT_EMAIL=%s", alertEmail),
		"",
		"# -- Slack --------------------------------------------------------------------",
		fmt.Sprintf("SLACK_WEBHOOK=%s", slackWebhook),
		"",
		"# -- Dashboard ----------------------------------------------------------------",
		fmt.Sprintf("DASHBOARD_URL=%s", dashboardURL),
		fmt.Sprintf("ALLOWED_ORIGINS=%s", dashboardURL),
		"",
		"# -- Scan config --------------------------------------------------------------",
		"SCAN_INTERVAL_HOURS=6",
		"DISABLED_MONITORS=",
		"",
		"# -- Intelligence API keys (configure in Settings after install) --------------",
		"HIBP_API_KEY=",
		"BREACH_DIRECTORY_KEY=",
		"LEAKCHECK_API_KEY=",
		"INTELX_API_KEY=",
		"LEAKLOOKUP_API_KEY=",
		"TELEGRAM_API_ID=",
		"TELEGRAM_API_HASH=",
		"PASTEBIN_API_KEY=",
		"PASTEBIN_API_USER_KEY=",
		"",
		"# -- Microsoft SSO (optional) -------------------------------------------------",
		"AZURE_CLIENT_ID=",
		"AZURE_TENANT_ID=",
		"",
		"# -- Environment --------------------------------------------------------------",
		"ENVIRONMENT=production",
		"",
	}, "\n")

	// Write UTF-8 without BOM — Python's dotenv requires this
	if err := os.WriteFile(envFile, []byte(content), 0600); err != nil {
		die("Failed to write .env: " + err.Error())
	}
	logSuccess(".env created at " + envFile)
	return true
}
